### ISSUE TITLE
Missing of CMakeLists.txt

### ISSUE THREAD

**Issue by Junfeng-Long** [Mehooz/vision4leg#11]
It seems that there is no CMakeLists.txt file in the folder third_party/unitree_legged_sdk.

**Comment by RchalYang** [comment]
Thank you for pointing it out, it's indeed missing several files, will fix it.

**Comment by Tie-1** [comment]
> Thank you for pointing it out, it's indeed missing several files, will fix it.

Excuse me, could you upload these documents?
