### ISSUE TITLE
Preparation of the realsense Camera

### ISSUE THREAD

**Issue by GGJulien** [Mehooz/vision4leg#3]
Hello,

Thanks a lot for providing this useful code. I want to test your code on our robot but I don't understand how should I run the camera? I have the real-sense software already installed and for example I can run realsense-viewer on the robot, is this sdk something that I should install in addition the others real-sense software? Do the code automatically will detect the camera?
Thanks a lot.

**Comment by RchalYang** [comment]
Hi, please check https://github.com/IntelRealSense/librealsense for pyrealsense2 installation. With pyrealsense2, you could read depth and rgb image from realsense mounted on the A1

**Comment by GGJulien** [comment]
Excellent! Thank you very much @RchalYang!

I'm just wondering what TensorRT version are you using on the robot?

That would be amazing if it is possible share the result of your pip list on the robot computer to see what are the dependency and their versions for real hardware. Thanks again.

**Comment by RchalYang** [comment]
Hi, we are using TensorRT 7.1.3 + CUDA 10.2  
Sorry our pip list on the robot is quite a mess, so it's probably not quite appropriate to share it.

**Comment by GGJulien** [comment]
Thank you very much @RchalYang. 
I just checked that our A1 robot has Jetpack 4.3 and CUDA 10 but I guess your Jetpack verion is 4.4 that you have CUDA 10.2.

Did you upgrade the Jetpack of the TX2 board to 4.4 of the A1 robot?If yes Do you remember how was the updating process? Since I afraid I break the whole software on TX2 board by upgrading the Jetpack.

The jetpack 4.3 works with old version of the PyTprch and TensorRT and then  torchRL also is not compatible with those version.

**Comment by RchalYang** [comment]
Hi, we did not upgrade the Jetpack.  I guess A1 robot come with different jetpack version.

**Comment by GGJulien** [comment]
Ok Thanks for the information!
