### ISSUE TITLE
Warning: NaN or Inf found in input tensor.

### ISSUE THREAD

**Issue by COST-97** [Mehooz/vision4leg#5]
Hi:
After I used this command`
python starter/ppo_locotransformer.py \
  --config config/rl/static/locotransformer/thin-goal.json \
  --seed 0 \
  --log_dir log \
  --id None
`
,I found that NaN or Inf found in input tensor.

`2022-05-31 10:30:41,273 MainThread INFO: EPOCH:0
2022-05-31 10:30:41,273 MainThread INFO: Time Consumed:184.63539457321167s
2022-05-31 10:30:41,273 MainThread INFO: Total Frames:16384s
Warning: NaN or Inf found in input tensor.
--------------------------------  -----------  -------  --------  --------
Name                              Value
Running_Average_Rewards           -54.81532
Train_Epoch_Reward                -2231.53607
Running_Training_Average_Rewards  nan
Explore_Time                      133.08431
Train___Time                      6.92088
Eval____Time                      44.60082
eval_traj_length                  1000.00000

Name                              Mean         Std      Max       Min
advs/mean                         -2.22717     0.03002  -2.12529  -2.28604
advs/std                          0.75737      0.02379  0.82605   0.69496
advs/max                          -0.16888     0.14757  -0.02466  -0.55419
advs/min                          -5.54139     0.42487  -4.92049  -6.12721
Training/vf_loss                  4.36672      0.87806  5.71956   2.46711
grad_norm/vf                      25.92703     6.66322  35.76588  15.57453
Training/policy_loss              0.01732      0.00343  0.02354   0.01051
logprob/mean                      3.95759      0.06009  4.06551   3.84129
logprob/std                       1.73187      0.05370  1.84179   1.59171
logprob/max                       6.79933      0.07294  6.90442   6.60392
logprob/min                       -5.01970     1.34194  -2.95232  -8.34160
log_std/mean                      -2.07996     0.00020  -2.07944  -2.08028
log_std/std                       0.00105      0.00068  0.00224   0.00000
log_std/max                       -2.07861     0.00062  -2.07751  -2.07954
log_std/min                       -2.08126     0.00105  -2.07944  -2.08303
ratio/max                         1.40505      0.10222  1.59550   1.01082
ratio/min                         0.69294      0.07199  0.99049   0.55098
grad_norm/pf                      2.21284      0.69023  3.47229   1.06191

Best Saved: -53.61613,  EPoch: 10
2022-05-31 10:54:03,264 MainThread INFO: EPOCH:10
2022-05-31 10:54:03,264 MainThread INFO: Time Consumed:1401.9698915481567s
2022-05-31 10:54:03,264 MainThread INFO: Total Frames:180224s
Warning: NaN or Inf found in input tensor.
--------------------------------  -----------  --------  ---------  ---------
Name                              Value
Running_Average_Rewards           -54.21573
Train_Epoch_Reward                -1585.07732
Running_Training_Average_Rewards  nan
Explore_Time                      1284.55944
Train___Time                      78.18600
Eval____Time                      39.18534
eval_traj_length                  1000.00000

Name                              Mean         Std       Max        Min
advs/mean                         -0.85172     0.67531   -0.00274   -2.03394
advs/std                          0.59794      0.10169   0.80672    0.43700
advs/max                          0.72025      0.54366   1.75742    -0.40045
advs/min                          -3.55583     1.09225   -1.45669   -5.79652
Training/vf_loss                  0.56694      0.73275   4.41500    0.16088
grad_norm/vf                      16.93190     20.29552  104.03627  0.37696
Training/policy_loss              0.01314      0.00664   0.02916    -0.00588
logprob/mean                      4.00094      0.06107   4.17171    3.82552
logprob/std                       1.74093      0.05428   1.87935    1.52889
logprob/max                       6.84385      0.06227   6.97969    6.65627
logprob/min                       -4.89748     1.52877   -2.04578   -10.62916
log_std/mean                      -2.08736     0.00443   -2.08030   -2.09498
log_std/std                       0.01243      0.00578   0.02193    0.00229
log_std/max                       -2.07844     0.00085   -2.07724   -2.07984
log_std/min                       -2.10350     0.01191   -2.08311   -2.12352
ratio/max                         1.52684      0.20323   2.32994    1.00307
ratio/min                         0.64219      0.10425   0.99667    0.40963
grad_norm/pf                      2.22837      0.65776   4.39971    0.87134
--------------------------------  -----------  --------  ---------  ---------

`

**Comment by RchalYang** [comment]
Hi, this is because at the beginning of the training, agent haven't collect a full trajectory to calculate the "Mean Training episode return". After a few epoch, this epoch will disappear. you can disregard this warning
