### ISSUE TITLE
Seems there is a possible bug in the setting of the time-step 

### ISSUE THREAD

**Issue by GGJulien** [Mehooz/vision4leg#7]
Hello,

I'm wondering how the control frequency work in the simulation, Because I see the following line for setting the pybullet time-step that is 0.001 s. 
    `  self._pybullet_client.setTimeStep(self._sim_time_step) `
https://github.com/Mehooz/vision4leg/blob/d80f9db796b2b7aa610733a821a7ff4167dfcd54/vision4leg/envs/locomotion_gym_env_with_rich_information.py#L342

and the we set the self._sim_time_step by a `sim_time_step_s` in: 

 https://github.com/Mehooz/vision4leg/blob/d80f9db796b2b7aa610733a821a7ff4167dfcd54/vision4leg/envs/locomotion_gym_env_with_rich_information.py#L154

that `sim_time_step_s` is set to be 0.001 in the following:
https://github.com/Mehooz/vision4leg/blob/d80f9db796b2b7aa610733a821a7ff4167dfcd54/vision4leg/envs/locomotion_gym_config.py#L27

So overall the pybullet time-step is 0.001, the reward calculation is based on time-step of 0.0025 s! Does it make sense? 
I think we are assuming that we apply the control input robot at every ` 16*0.0025 ` but actually we are applying at every `16*0.001` s to pybullet.

Another question that I have  there a way to stop training and running again from the previous training time? Continuing training from the previous trained network?

Thanks a lot for your time.

**Comment by RchalYang** [comment]
Hi, Thanks for pointing this out. We might miss this part, but since it only affect the reward calculation, it's fine. It just scale the reward by a constant (and which is the same case for all method). 

And for the conitnuing training part. we currently did not support that in this codebase, you can probably add it yourself.

**Comment by GGJulien** [comment]
Thank you very much for the information. Yes that makes sense and will not change the whole behavior.
